// Copies contract ABIs (and the bytecode of the few contracts the rehearsal deploys) from Foundry's build output
// into typed modules. Run `forge build` in ../contracts first.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const out = join(root, "..", "contracts", "out");
const target = join(root, "src", "abi");

// [source file, contract name, include bytecode]
const artifacts = [
  ["ForecastRegistry.sol", "ForecastRegistry", false],
  ["OracleAdapter.sol", "OracleAdapter", false],
  ["OracleAdapter.sol", "IAggregatorV3", false],
  ["SeasonRewards.sol", "SeasonRewards", false],
  ["Treasury.sol", "Treasury", false],
  ["VotingEscrow.sol", "VotingEscrow", false],
  ["TenaxToken.sol", "TenaxToken", false],
  ["LiquidityVault.sol", "LiquidityVault", false],
  ["RevenueRouter.sol", "RevenueRouter", false],
  ["FeeDistributor.sol", "FeeDistributor", false],
  ["MerkleAirdrop.sol", "MerkleAirdrop", false],
  ["LaunchFeeHook.sol", "LaunchFeeHook", false],
  ["MockAggregator.sol", "MockAggregator", true],
  ["V4Swapper.sol", "V4Swapper", true],
];

mkdirSync(target, { recursive: true });
const exports = [];
for (const [file, name, withBytecode] of artifacts) {
  const artifact = JSON.parse(readFileSync(join(out, file, `${name}.json`), "utf8"));
  const id = name[0].toLowerCase() + name.slice(1);
  let body = `// Generated by scripts/abi.mjs from contracts/out/${file}/${name}.json. Do not edit.\n`;
  body += `export const ${id}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  if (withBytecode) body += `\nexport const ${id}Bytecode = "${artifact.bytecode.object}" as const;\n`;
  writeFileSync(join(target, `${name}.ts`), body);
  exports.push(`export * from "./${name}.js";`);
}
writeFileSync(join(target, "index.ts"), `// Generated by scripts/abi.mjs. Do not edit.\n${exports.join("\n")}\n`);
console.log(`wrote ${artifacts.length} ABIs to src/abi`);
